// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcrtjpLMQbPxoZIssYxuccAua9PF-ggU',
    appId: '1:148713167278:web:0e7ad3cdf895e8ac8cd03f',
    messagingSenderId: '148713167278',
    projectId: 'gudz-a5d02',
    authDomain: 'gudz-a5d02.firebaseapp.com',
    storageBucket: 'gudz-a5d02.appspot.com',
    measurementId: 'G-V497EK2S95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwxvXQnw0Sprvx5R1EiNwvnIcep0q85tI',
    appId: '1:148713167278:android:d777bb7b8a293bff8cd03f',
    messagingSenderId: '148713167278',
    projectId: 'gudz-a5d02',
    storageBucket: 'gudz-a5d02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSyTv4-GTYxBdBn460TCps-u9Ot1Bn3uc',
    appId: '1:148713167278:ios:ef7c2385ba47dcba8cd03f',
    messagingSenderId: '148713167278',
    projectId: 'gudz-a5d02',
    storageBucket: 'gudz-a5d02.appspot.com',
    iosClientId: '148713167278-2t73hclkjpuipar2ej1mc6m4i3ra10ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSyTv4-GTYxBdBn460TCps-u9Ot1Bn3uc',
    appId: '1:148713167278:ios:ef7c2385ba47dcba8cd03f',
    messagingSenderId: '148713167278',
    projectId: 'gudz-a5d02',
    storageBucket: 'gudz-a5d02.appspot.com',
    iosClientId: '148713167278-2t73hclkjpuipar2ej1mc6m4i3ra10ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
